# Generated by Django 2.2.5 on 2020-04-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videorequest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='vodeotitle',
            new_name='videotitle',
        ),
    ]
